### ISSUE TITLE
We need to decide on the direction we want to go with these images

### ISSUE THREAD

**Issue by pbering** [Sitecore/docker-images#18]
When I started the original repostory the idea was to provide a *easy* way for anyone to build and host their own Sitecore base Docker Images with a few goals for each image:

1. Should be build using standard tooling (unzip for Sitecore 8.2.x and SIF for Sitecore 9.x)
1. Should only do just enough to be able to run on its own
1. Should be used as BASE images to build variants and projects on

The path we are currently on diverts from goal 2 and especially 3 and it started with https://github.com/Sitecore/docker-images/pull/13. Not that it is bad at all but in my opinion it should have been implemented as a "variant" instead of in the base image. My current problem is that I can't use images from this repository anymore as I intended to do, for example I can't just do `FROM registry.mycompany.com/sitecore:9.0.171219-xm1-cm` and COPY in my project code, push and run in dev/test/prod whatever, without accepting multiple GB of Sitecore files on *each* Docker host spread in different volumes.

I would suggest that we use this issue to discuss what we want to do. For starters I suggest the we:

1. Adopt above goals
1. Restrucure this repository like so (where each folder is also the Docker repository name):
  /sitecore-base/
  /sitecore-variant/ or /sitecore-dev/ if it turns out it's only variants used for development
  /solrwin-dev/
  /sqlwin-dev/
1. Do the PowerShell module for builds as discussed in issue #17 and support that we build only on folder (so our uses can choose which Docker repositories they want, or just call build multiple times to get it all)

Thoughts?

**Comment by joostmeijles** [comment]
@pbering I agree with your proposal. We should have base images that do the minimal, on top of that variants may be defined. 

By having a clear purpose per image and a re-use design (according to the above proposed rules) we keep it easy-to-use and maintainable.

**Comment by saberone** [comment]
Your proposal sounds like a no-brainer to me! Especially if the use case is "Provide a base image that accelerates Sitecore/Docker development".

**Comment by istern** [comment]
We shouldn't have one image to rule them all, but smal base images and build on top with what ever variant needed.

**Comment by jeanfrancoislarente** [comment]
The docker-images repo doesn't have to be "just" base images, but we can certainly have various version filters that can be used when running the build scripts to create images. 

Some people can use the repo to create "base" images and others can create more elaborate multi-stage images.

The suggestion to have volumes, etc makes sense if those images are going to be practical for a dev team. The data should be mounted outside of the images for dev and then perhaps QA uses a base blank image and deploys solution overtop. 

QA would be most likely to spin up and tear down images without keeping anything behind. The idea of the license not being in the image just makes sense from the aspect of having docker images "immutable" as well.

I like the discusion though and agree with your proposed direction @pbering -

**Comment by pbering** [comment]
@jeanfrancoislarente agreed on the license part, that part we should change in the base images. I'm thinking that instead of making the whole data folder a volume, we should have a single folder just for the license file and then configure Sitecore to use that. This will force us to always mount a volume with a license in it (by default) OR copy it in in our private project images.

**Comment by pbering** [comment]
@Ben-m-s thanks for your comment!

To clarify a few things:

1. Goal 2 "Should only do just enough to be able to run on its own": With "able to run" is not necessary also meaning that it *just* works if it was started with `docker run`'. My point is that the Dockerfile of a BASE image should as closely as possible mimic the installation of Sitecore following the official guidelines, so close that you *could* execute the same RUN commands our your own machine and get Sitecore installed. Some things needs to be different though, like skipping the Solr steps and modifying the config.json so that SQL operations are also skipped. It's clearly a balance between when enough is enough and I think that for example setting default sql server name is OK since that is something that often would be the same locally across different projects (by container linking). But I do also think that the current (and original) does a bit *too much* to be BASE images!

2. Regarding the SQL and Solr images: These images are purely intended for local development / test environments, also why I proposed that they should be named "sqlwin-dev" and "solrwin-dev". For production use I would not seed default data into volumes like that.

...and to continue the discussion, here is diagram on how I have envisioned theses images to be structured (hopefully use full for further discussions):

```text

A -->                     microsoft/aspnet:4.6.2
                                     |
                                     |
B -->           sitecore-internal:9.0.1 (only SIF and dependencies)
              /                       \                             \
             /                         \                             \
C -->    sitecore-base:9.0.1-xm1-cm    sitecore-base:9.0.1-xm1-cd    sitecore-base:9.0.1-xm1-exm-dispatch
            |                           |                             |
            |                           |                             |
D -->    (your-own-project-here)       (your-own-project-here)       (your-own-project-here)
            |                           |                             |
         or variants like...           etc.                          etc.
            |
            |
         sitecore-dev:9.0.1-xml-cm <--- Could have VOLUME's for the whole data/website folder and fx. seed data...

A == Scratch Layer
B == Internal Layer
C == Base Layer
D == Variant Layer / Project Layer
```

**Comment by jeanfrancoislarente** [comment]
There's further opportunity to layer (or at least to explain how to layer) for things such as additional modules (SPE, SXA, etc) to keep layers as small as possible.

Between C & D you could have a layer for modules. That way you're not stuck with base images containing modules or project layer having to install modules

**Comment by pbering** [comment]
"So I guess starting at D you can have D1, D2, D3 levels."

Yes that's the plan, from D and down you choose where to base your project from 🙂

**Comment by jeanfrancoislarente** [comment]
Based on the above - we should probably have a base solr image (solr-install only) without any Sitecore/SIF items deployed?
Then when we do an XM vs XP vs XC we're building up from the same base solr image?

**Comment by Ben-m-s** [comment]
@pbering, thanks a lot for this diagram.

You made a great job providing this high-level definition. I like the structure and the way you presented it with plain text (it is a work of art).

I would suggest to include in level B "configuring IIS with the typical settings required by the installation guide". You may have already thought about it when you said "dependencies".

Leaving the existing SQL and Solr images for development purposes may be fine, although I would not discard creating other versions that may solve a wide range of "common" scenarios, simplifying this way, many common Sitecore deployments. For instance, installing a cluster with 3 Solr servers with HA (using Zookeeper) for a Sitecore solution may be a common scenario for many mid-size clients. Setting this environment up is time-consuming, and if you need to do it in QA, UAT, and PROD then it can take days. It would be a game changer if we could do it in an hour and with much less required knowledge. Just plug and play.

I see Docker as a technology that can really change how things are done, having a big impact in costs allowing us to dedicate our client's budgets to more added-value work. And it would be nice if we could really simplify Sitecore deployments.

We may not need to create some images, such as the Solr ones, as they may already be available somewhere. I'm just talking about ideas mid-term objectives.

Coming back to the subject of the Sitecore base images (level C), it would be nice to drill a bit dipper in the requirements for specific scenarios. IMHO requirements should be defined based on the needs of the desired solution. As long as the effort required to meet the requirements and maintainability of the final solution is reasonable, we should not be afraid of changing the way things are done.

Containers completely change the way deployments are done. In a traditional system, updates are applied by modifying existing servers. However, changes to a system made of containers are done by creating new containers and replacing the old ones with them. There will be no more modifications to existing running servers. Somehow, Docker implicitly brings a "staging" deployment model where new challenges, such as persistence, need to be addressed.

As the new model is different, we need to think in a different way. When running containers are replaced by new ones, we may want to keep the state of the system, which is stored in the data folder (even in the "temp" folder). We may not want to re-build Solr cores (or "collections" in an HA cluster). Even if we have created a Sitecore installation package to move items from production to other environments (DEV, QA, UAT) for testing or debugging purposes, we may want to preserve the definition of those packages (along with the package itself) even if the container is replaced. We may even think about the IIS logs, which are very useful in diagnosing issues. We may want to keep that information even when deployments (which may be small) are done. 

In the traditional Sitecore deployment model, the concept of image inheritance doesn't exist. The Sitecore installation documents assume that you are installing from scratch from the very beginning to the end. There is no concept of image inheritance. And this new concept can be invaluable for reusability.

Let's see an example of a typical scenario where more than one content manager or content delivery must be deployed in a scaled environment. In order to do it, some configuration changes may need to be done based on arguments passed by the docker-compose files (or any orchestrating technology). It is the case, for instance, of the setting "Analytics.HostName". Base images ideally should facilitate that inheriting images/containers can do these changes as easier as possible. 

With that said, my opinion regarding the statement "_the Dockerfile of a BASE image should as closely as possible mimic the installation of Sitecore following the official guidelines_" is as follows:

In order to make Dockerfiles as intuitive as possible, we should make an effort to follow the above principle. However, the main requirements should be determined by the new future needs, based on how thing will work with Docker, and not based on how things are done now.


I suggest that we work on the following topics from a conceptual point of view:

 - Overall architecture. How a System should look like, with all its environments (DEV, QA, UAT, and PROD).
    - How many containers/host
    - What containers/roles should be on each host
    - Network requirements among them
    - Hybrid scenarios. For instance, services such as SQL Server can be Azure SQL databases instead of containers.

 - State assets (databases, diagnostics folder, logs folder, serialization folder, packages folder, viewstate folder, temp folder, Solr cores/collections, IIS logs, ...):
   - Where State assets should be stored.
   - How State assets should be installed in a clean environment.
   - How State assets should be managed (in both scenarios: being in or out the container)
     - How to get Sitecore logs when needed for debugging
     - How to get diagnostic data when needed
     - What happens if the container gets corrupted or stop working. How to get its relevant data
     - How to update existing State assets during new feature deployments
     - ...

 - Scaling options:
     - Shall the base images support automatic scaling out?

 - Analytics:
     - Services such as Azure OMS are very useful in systems hosted in Azure. It may be nice to take advantage of it, using containers.

Sorry for the long comment. I hope it helps.

**Comment by pbering** [comment]
>You made a great job providing this high-level definition. I like the structure and the way you presented it with plain text (it is a work of art).

Thanks! :)

>I would suggest to include in level B "configuring IIS with the typical settings required by the installation guide". You may have already thought about it when you said "dependencies".

Yes B should also include settings that makes sense or otherwise helps inherited images.

>I see Docker as a technology that can really change how things are done, having a big impact in costs allowing us to dedicate our client's budgets to more added-value work. And it would be nice if we could really simplify Sitecore deployments.

Couldn't agree more!

>Containers completely change the way deployments are done. In a traditional system, updates are applied by modifying existing servers. However, changes to a system made of containers are done by creating new containers and replacing the old ones with them. There will be no more modifications to existing running servers. Somehow, Docker implicitly brings a "staging" deployment model where new challenges, such as persistence, need to be addressed.

Agreed, but I don't think if would call it a "staging" deployment model, but more a immutable deployment model.

>As the new model is different, we need to think in a different way. When running containers are replaced by new ones, we may want to keep the state of the system, which is stored in the data folder (even in the "temp" folder). We may not want to re-build Solr cores (or "collections" in an HA cluster). Even if we have created a Sitecore installation package to move items from production to other environments (DEV, QA, UAT) for testing or debugging purposes, we may want to preserve the definition of those packages (along with the package itself) even if the container is replaced. We may even think about the IIS logs, which are very useful in diagnosing issues. We may want to keep that information even when deployments (which may be small) are done.

Agreed on the data part (sql database, solr cores etc.) but Sitecore log files should be shipped else where (to fx ElasticSearch) and the same goes for IIS (and what ever web server you be putting in front). For a CM server I see no problem in mounting the data folder if you want to keep it around between deployments (I prefer not to). But update package installation history is stored in the TEMP folder (mixed up with other "irrelevant" files) and that might be something that we need to look into solving in a nice way. Could be a scheduled Sitecore job that moved the files into a more suitable location.

>Let's see an example of a typical scenario where more than one content manager or content delivery must be deployed in a scaled environment. In order to do it, some configuration changes may need to be done based on arguments passed by the docker-compose files (or any orchestrating technology). It is the case, for instance, of the setting "Analytics.HostName". Base images ideally should facilitate that inheriting images/containers can do these changes as easier as possible.

Yes runtime dependent configuration like your example could be handled with plain old environment variables defined like `<setting name="Analytics.HostName" value="$(env:SC_ANALYTICS_HOSTNAME)" />` (has been supported in Sitecore since 8.2). I think we should dig into which exact variables that would make sense to expose in the BASE images as ENV in the Dockerfiles!

>Shall the base images support automatic scaling out?

What do you mean by that? Support it how?

...regarding the rest of "I suggest that we work on the following topics from a conceptual point of view:"

I agreed that this is documentation / guidance work that needs to be done but I do think that it belongs elsewhere maybe another repository where we also could have sample Docker Swarm stacks (and Kubernetes when the Windows support comes out of beta), ARM/CF/Terraform template, wiki pages etc. Much like the /Sitecore/docker-demo repo but for architectural production grade guidance.
