### ISSUE TITLE
Enable commerce engine containers to log to STDOUT using filebeat

### ISSUE THREAD

**Issue by reyrahadian** [Sitecore/docker-images#181]
Hi folks, I've been using the 9.2.0 XC containers and noticed that it's not outputting the logs to STDOUT the same way as CM/CD container does. 

From what I can gather in the 9.2.0 CM/CD Dockerfiles where it uses UDP protocol to output the logs and have filebeat listening to the specified port, Commerce Engine containers should be able to use the same approach. For this to work for Commerce Engine, it would need to be using the Serilog.Sinks.Udp NuGet package and have the config.json files updated to include the UDP setting.

I'm happy to raise a PR if this approach is reasonable.

**Comment by pbering** [comment]
Hi there. I will say that it sounds like a good approach and it's ok to inject config/binaries in the entrypoint scripts (since they are opt-in and overrideable by the user). @joostmeijles do you see any problems with this approach? Else I think you should good ahead with a PR, would be a good feature :)
