### ISSUE TITLE
Configure an option for parallel package download

### ISSUE THREAD

**Issue by michaellwest** [Sitecore/docker-images#203]
My assumption is that the source server bandwidth is lower than the target bandwidth. Perhaps 2 or 3 would be a good default. Use write-progress to help provide feedback.

**Comment by pbering** [comment]
Could be a good addition but I don't think it worth the effort and the maintenance afterward, how often do the Invoke-PackageRestore actual download anything after the first run?

Last year when we did the "assets" image, the first implementation did the downloads inside the image, parsing in dev.sitecore.net credentials as build-args, but we had to remove that again since people was struggling with bandwidth related issues.

**Comment by michaellwest** [comment]
Sounds good. Thanks for the feedback.
