### ISSUE TITLE
Separate assets image for each topology

### ISSUE THREAD

**Issue by michaellwest** [Sitecore/docker-images#233]
The following changes could reduce the download time before getting started and shrink the asset image size.

Create an asset image for xm, xp, xc - this should reduce the need to download packages that are not needed for your builds. Right now someone building xm has to download at least 2 GB of packages which are not required.

**Comment by pbering** [comment]
It's a fine balance :)

1. Before the asset images, all WDP's defined as "sources" in build.json was copied from InstallSourcePath to the Docker build context folder in **each** image == massive amount of duplicate WDP's since many images uses the same WDP's (uses ~30 GB on disk), but building everything takes less time.
1. Placing **all** WDP's for every version in 1 asset image == too large image, close to 20 GB, but takes less time to build the rest.
1. Per version asset images (as today) == quite balanced compared to above.

Per version **and** topology as you suggest _could_ give some benefits to those that only builds specific versions and typologies but for those building everything I don't see the benefits? You would still have duplicate WDP's in the version+topology asset images, such as SPE, JSS, SXA and PS which would be in XM, XP and XC right?

**Comment by bakgaard** [comment]
Perhaps ``sources`` could be filtered like ``tags`` are filtered from ``.\Build.ps1``? 

Perhaps a parameter could be passed to specify it?

**Comment by bplasmeijer** [comment]
> It's a fine balance :)
> 
> 1. Before the asset images, all WDP's defined as "sources" in build.json was copied from InstallSourcePath to the Docker build context folder in **each** image == massive amount of duplicate WDP's since many images uses the same WDP's (uses ~30 GB on disk), but building everything takes less time.
> 2. Placing **all** WDP's for every version in 1 asset image == too large image, close to 20 GB, but takes less time to build the rest.
> 3. Per version asset images (as today) == quite balanced compared to above.
> 
> Per version **and** topology as you suggest _could_ give some benefits to those that only builds specific versions and typologies but for those building everything I don't see the benefits? You would still have duplicate WDP's in the version+topology asset images, such as SPE, JSS, SXA and PS which would be in XM, XP and XC right?

I want to suggest the following approach, 

FROM ${MODULE1_IMAGE} as module1
FROM ${MODULE2_IMAGE} as module2

FROM ${BASE_IMAGE}

COPY –-from=module1 \package c:\\temp\\package
RUN c:\temp\package\Install-Package.ps1

COPY –-from=module2 \package c:\\temp\\package
RUN c:\temp\package\Install-Package.ps1

**Comment by jeanfrancoislarente** [comment]
This is no longer relevant in 10.x + - can we close this @michaellwest ?

**Comment by michaellwest** [comment]
Sure. No problem.
