### ISSUE TITLE
Delete Sitecore packages after build

### ISSUE THREAD

**Issue by jeanfrancoislarente** [Sitecore/docker-images#5]
In order to save space locally, the build process should delete the packages zip that is copied into each /Sitecore subfolder after each build.

**Comment by pbering** [comment]
It's "by design" and it is used for caching so the build dosn't have to retrieve the packages on every build. In my case the packages is on a network file share and my build *also* runs every Sunday to build fresh images with OS patches from the Microsoft bases images.

If needed we could add a switch parameter on Build.ps1 to handle if it should be cached or not.

**Comment by jeanfrancoislarente** [comment]
The zip files end up in 2 places though. In the "repository". In the $InstallSourcePath and then copied to each of the /sitecore/<folder>.
I'm proposing to delete from the local version otherwise in the case where you're on a local machine, you end up with _many_ copies of the same assets. One in the repo and 1 for each configuration that uses the package.
